password = [
    48,
    48,
    117,
    67,
    56,
    87,
    43,
    109,
    68,
    74,
    65,
    97,
    89,
    57,
    104,
    118,
    97,
    65,
    69,
    100,
    89,
    75,
    106,
    47,
    116,
    115,
    70,
    119,
    102,
    106,
    70,
    121,
    43,
    43,
    76,
    113,
    108,
    108,
    103,
    56,
    109,
    86,
    49,
    98,
    113,
    71,
    66,
    52,
    53,
    104,
    84,
    101,
    54,
    102,
    56,
    78,
    67,
    99,
    51,
    117,
    106,
    78,
    88,
    52,
    119,
    78,
]
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = false
enable-file-copy-paste = true
show_quality_monitor = false
follow_remote_cursor = false
follow_remote_window = false
keyboard_mode = 'map'
view_only = false
sync-init-clipboard = false

[options]
custom-fps = '30'
codec-preference = 'auto'
touch-mode = ''
collapse_toolbar = 'Y'
zoom-cursor = ''
alias = 'Sever Desktop'
swap-left-right-mouse = ''
i444 = ''

[ui_flutter]

[info]
username = 'SMITJ15'
hostname = 'colas50988'
platform = 'Windows'

[transfer]
write_jobs = []
read_jobs = []
