password = [
    48,
    48,
    52,
    109,
    78,
    83,
    79,
    50,
    76,
    100,
    80,
    120,
    104,
    82,
    69,
    104,
    120,
    116,
    83,
    68,
    77,
    68,
    114,
    88,
    70,
    90,
    111,
    104,
    87,
    66,
    68,
    122,
    54,
    70,
    89,
    74,
    102,
    49,
    72,
    76,
    55,
    85,
    113,
    57,
    114,
    50,
    82,
    48,
    117,
    97,
    110,
    51,
    47,
    85,
    117,
    109,
    111,
    115,
    56,
    97,
    85,
    78,
    83,
    43,
    43,
    100,
]
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = false
enable-file-copy-paste = true
show_quality_monitor = false
follow_remote_cursor = false
follow_remote_window = false
keyboard_mode = 'map'
view_only = false
sync-init-clipboard = false

[options]
touch-mode = ''
alias = 'Sever Desktop'
i444 = ''
custom-fps = '30'
swap-left-right-mouse = ''
codec-preference = 'auto'
zoom-cursor = ''

[ui_flutter]
wm_RemoteDesktop = '{"width":1258.0,"height":1382.0,"offsetWidth":2370.0,"offsetHeight":46.0,"isMaximized":false,"isFullscreen":false}'

[info]
username = 'SMITJ15'
hostname = 'colas50988'
platform = 'Windows'

[transfer]
write_jobs = []
read_jobs = []
