rendezvous_server = 'rusty.jarrodsmith.website:21116'
nat_type = 1
serial = 0
unlock_pin = ''
trusted_devices = ''

[options]
allow-remote-config-modification = 'Y'
custom-rendezvous-server = 'rusty.jarrodsmith.website'
local-ip-addr = '192.168.236.32'
av1-test = 'Y'
key = 'Oj1wE2Ia7j5C3uz3qg7R0MmeeNqgn4OGZsa4IXoVnhs='
